# POS project 1
# author: Martin Hruska
# e-mail: xhrusk16@stud.fit.vutbr.cz

CC=gcc
CFLAGS=-Wall -ansi -Wextra -g -O
PROJ=proj01

all: $(PROJ)

$(PROJ): $(PROJ).c
	$(CC) $(CFLAGS) $(PROJ).c -o $@

clean:
	rm $(PROJ)
