# project: Projec 3 @ POS
# author: Martin Hruska
# e-mail: xhrusk16@stud.fit.vutbr.cz
CC=gcc
CFLAGS=-Wall -Wextra -ansi -lpthread
PROJ=proj03

all: $(PROJ)

$(PROJ): $(PROJ).c
	$(CC) $(CFLAGS) $(PROJ).c -o $@

clean:
	rm $(PROJ)
